version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      MONGO_USER: ${MONGO_USER}
      PORT: 3000
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:3.6.2
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"